Python/django/Essentials/django-essentials/Essentials/Essentials/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^resource/', include('resource.urls')),
    url(r'^admin/', admin.site.urls),
]

Python/django/Essentials/django-essentials/Essentials/resource/urls.py
from django.conf.urls import url, include, patterns

from wiki.urls import get_pattern as get_wiki_pattern
# from wiki.urls import include
from django_nyt.urls import get_pattern as get_nyt_pattern

from . import views

app_name = 'resource'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # url(r'^wiki/', include('wiki.urls'), namespace='wiki'),
]

urlpatterns += [
    url(r'^notifications/', get_nyt_pattern()),
    url(r'^wiki', get_wiki_pattern())
]

Python/django/Essentials/django-essentials/Essentials/resource/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
    	return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class Make(models.Model):
    make_name = models.CharField(max_length=30)
    pub_date = models.DateTimeField('date published')
    def __str__(self): 
        return self.make_name
    # Make.admin_order_field = 'make'

class Model(models.Model):
    make_name = models.ForeignKey(Make, on_delete=models.CASCADE)
    model_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    def __str__(self):
        return self.model_name

Python/django/Essentials/django-essentials/Essentials/resource/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.
# def index(request):
# 	return HttpResponse("Hello, world. You're at the resource index.")

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'resource/detail.html', {'question': question})

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	# template = loader.get_template('resource/index.html')
# 	context = {
# 		'latest_question_list': latest_question_list,
# 	}
# 	return render(request, 'resource/index.html', context)

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'resource/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('resource:results', args=(question.id,)))

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'resource/results.html', {'question': question})

class IndexView(generic.ListView):
	template_name = 'resource/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""Return the last five published questions."""
		return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'resource/detail.html'

	def get_Queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'resource/results.html'

def get_queryset(self):
	"""
	Return the last five published questions (not including those set to be published in the future).
	"""
	return Question.objects.filter(
		pub_date__lte=timezone.now()
	).order_by('-pub_date')[:5]

Python/django/Essentials/django-essentials/Essentials/resource/templates/resource/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'resource:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

Python/django/Essentials/django-essentials/Essentials/resource/templates/resource/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'resource/style.css' %}" />

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'resource:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No resources are available.</p>
{% endif %}

Python/django/Essentials/django-essentials/Essentials/resource/templates/resource/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'resource:detail' question.id %}">Vote again?</a>

Python/django/Essentials/django-essentials/Essentials/templates/wiki/base.html
{% extends "wiki/base_site.html" %}

{# Intentionally empty, to allow easy customization with no copy-paste #}

Python/django/Essentials/django-essentials/Essentials/templates/wiki/base_site.html
{% load sekizai_tags i18n wiki_tags %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block wiki_pagetitle %}{% endblock %}{% block wiki_site_title %} - django-\/\/  i K |{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="www.django-wiki.org">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}wiki/bootstrap/css/wiki-bootstrap.min.css" rel="stylesheet">

    {% render_block "css" %}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    {% block wiki_body %}

    {% block wiki_navbar %}
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block wiki_header_branding %}
          <a class="navbar-brand" href="{% url 'wiki:root' %}">django-\/\/ i K |</a>
          {% endblock %}
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" id="wiki-search-form" method="GET" action="{% url 'wiki:search' %}">
            <div class="input-group">
              <input type="search" class="form-control search-query" name="q" placeholder="{% trans "Search..." %}" />
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span class="fa fa-search"></span>
                </button>
              </span>
            </div><!-- /input-group -->
          </form>
          <div class="navbar-right">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="badge notification-cnt">0</span>
                  {{ user }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'wiki:logout' %}">
                      <i class="fa fa-power-off"></i>
                      {% trans "Log out" %}
                    </a>
                  </li>
                  {% if user.is_superuser %}
                  <li>
                    <a href="{% url 'wiki:deleted_list' %}">
                      <i class="fa fa-trash-o"></i>
                      {% trans "Deleted articles" %}
                    </a>
                  </li>
                  {% endif %}
                  {% if "wiki.plugins.notifications"|plugin_enabled %}
                    {% include "wiki/plugins/notifications/menubaritem.html" %}
                  {% endif %}
                </ul>
              </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
              <li>
                <a href="{% login_url as wiki_login_url %}{{ wiki_login_url }}">{% trans "Log in" %}</a>
              </li>
              <li>
                <a href="{% url 'wiki:signup' %}">{% trans "Sign up" %}</a>
              </li>
            </ul>
            {% endif %}
          </div>
          {% block wiki_header_navlinks %}
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">{% trans "Home" %}</a></li>
            <li><a href="https://github.com/django-wiki/django-wiki" target="_blank">{% trans "About" %}</a></li>
          </ul>
          {% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container" style="margin-top: 60px;">

      {% if messages %}
        <!-- Messages for this instance -->
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <!-- Reserved for breadcrumbs -->
      {% block wiki_breadcrumbs %}{% endblock %}

      <!-- Main page contents go here -->
      {% block wiki_contents %}{% endblock %}

      <footer id="wiki-footer">
        <hr />
        {% block wiki_footer_logo %}
        <a href="https://github.com/django-wiki/django-wiki" class="pull-right"><img src="{{ STATIC_URL }}wiki/img/github_icon.png" /></a>
        {% endblock %}
        {% block wiki_footer_prepend %}
        {% endblock %}
        <p>{% blocktrans %}Powered by <a href="http://www.django-wiki.org">django-wiki</a>, an open source application under the <a href="http://www.gnu.org/licenses/quick-guide-gplv3.html">GPLv3</a> license. Let knowledge be the cure.{% endblocktrans %}</p>
        <div style="clear: both"></div>
      </footer>
      </div>

    </div> <!-- /container -->

    {% endblock %}

    <script src="{{ STATIC_URL }}wiki/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}wiki/js/core.js"></script>
    <script src="{{ STATIC_URL }}wiki/bootstrap/js/bootstrap.min.js"></script>
    <!-- Optionally enable responsive features in IE8 -->
    <script src="{{ STATIC_URL }}wiki/js/respond.min.js"></script>
    {% render_block "js" %}

  </body>
</html>